# Generated by Django 5.0 on 2024-06-28 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_booking_booking_datetime_alter_trip_end_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='age',
        ),
    ]
