# Generated by Django 5.0 on 2024-06-29 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_tripprice_trip_alter_tripprice_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripprice',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='trip_price_trip', to='organization.trip'),
        ),
    ]
