# Generated by Django 5.0 on 2024-07-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_tripprice_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_file',
            field=models.FileField(max_length=200, upload_to=''),
        ),
    ]
