# Generated by Django 5.0 on 2024-07-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_ticket_ticket_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_file',
            field=models.FileField(max_length=200, upload_to='tickets/'),
        ),
    ]
