# Generated by Django 5.0 on 2024-07-26 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushAlertNotification',
        ),
    ]
