# Generated by Django 5.0 on 2024-07-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0006_pushalertnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushAlertNotification',
        ),
    ]
