# Generated by Django 5.0 on 2024-06-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_organization_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
